/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
import {SWMessageType} from './types'
import {connectDB, DB, KEYS} from './db/db-helper';

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => {
    const path = url.pathname;	
    return url.origin === self.location.origin &&	
      (path.endsWith('.png') || path.endsWith('.ico') || path.endsWith('manifest.json'));
  },

  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: 'static-miscs',
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', async (event) => {
  if (event.data) {	
    const {type, data} = event.data;
    switch (type) {
      case 'SKIP_WAITING': {
        self.skipWaiting();
        return;
      }
      case SWMessageType.PAGE_LOADS: {	
        await connectDB(1);
        const [mypd, cny, cat] = await Promise.all([
          DB.get(KEYS.mypd),
          DB.get(KEYS.filterCNY),
          DB.get(KEYS.filterCAT)
        ]);
        
        const pdCurFilter = Object.assign({},
          !!cny && {cny},
          !!cat && {cat}
        );
        const data = {
          mypd,
          pdCurFilter
        };
        self.clients.matchAll().then(clis => {	
          clis.forEach(c => {	
            c.postMessage({type: SWMessageType.SEND_PAGE_INIT_DATA, data})	
          });	
        });	
        break;	
      }	
      case SWMessageType.SET_DB_MY_PD: {	
        await DB.set(KEYS.mypd, data);
        break;	
      }    
      case SWMessageType.SET_DB_FILTER_COUNTRY: {
        await DB.set(KEYS.filterCNY, data);
        break;
      }
      case SWMessageType.SET_DB_FILTER_CATEGORY: {
        await DB.set(KEYS.filterCAT, data);
        break;
      }
      default:	
        break;	
    }	
  }
});

self.addEventListener('install', (event) => {	
  console.log('service worker installed, skip waiting');	
  self.skipWaiting();	
});

self.addEventListener('activate', async (event) => {	
  console.log('service worker activated');	
  await connectDB(1);	
  const [mypd, cny, cat] = await Promise.all([
    DB.get(KEYS.mypd),
    DB.get(KEYS.filterCNY),
    DB.get(KEYS.filterCAT)
  ]);
  const pdCurFilter = Object.assign({},
    !!cny && {cny},
    !!cat && {cat}
  );
  const data = {
    mypd,
    pdCurFilter
  };
  self.clients.matchAll().then(clis => {
    clis.forEach(c => {	
      c.postMessage({type: SWMessageType.SEND_PAGE_INIT_DATA, data});
    });
  });
});
